### ISSUE TITLE
The Services layout is not responsive.

### ISSUE THREAD

**Issue by izmeez** [stpaultim/services_recipe#1]
Testing the services_recipe the `Views:Services` Block display is not responsive. It appears as three columns even on narrow displays. Maybe that is to be expected until css is added? I'm just adding this issue to track it.

**Comment by stpaultim** [comment]
@izmeez - Thanks, that is something that needs to be addressed. Thanks for opening an issue to make sure that we deal with it and THANKS for testing the recipe!

**Comment by stpaultim** [comment]
@izmeez This has been fixed.
