### ISSUE TITLE
Make Views:Services grid default settings 4 columns.

### ISSUE THREAD

**Issue by izmeez** [stpaultim/services_recipe#2]
The Views:Services grid settings default to 3 columns which is the same as the Backdrop default cards view and a common trend these days. 

However, I would like to suggest using a default of four. A default of 4 allows for a greater variety of useful appearances on devices from narrow/phone = single column, landscape/tablet portrait = two columns and wide/tablet landscape = four columns. And is a common application of 12-column grid templates and can be extended in multiples of even numbers.

It will require expanding the default component block display to four from three.

**Comment by stpaultim** [comment]
@izmeez 

Thanks for this suggestion. I decided to base this theme on an existing Wordpress theme, to leverage an existing design that feels good and useful and to save us the time of creating an entirely new design. In the Wordpress theme we are using, they use 3 columns as the default for the services section, so I start there. 

![image](https://github.com/stpaultim/services_recipe/assets/3144571/3b2189a0-f7e2-4b09-9060-321657d5ddab)

However, I do not want to lock us into adhering to the Wordpress design precisely and am open to making changes where it makes sense. 

I think the risk of going to 4 columns is that you need 4 or 8 or 12 items to get multiple even rows. With three columns - 3, 6, 9, or 12 all result in even rows. So three columns seems more versital to start with. 

We could make sure that the theme supports both 3 and 4 columns and even provide some instructions to make it easy for someone to switch between 3 and 4 columns. I'm not wed to 3 columns and will see if anyone else has an opinion on this.

I may even go so far as to try 4 columns and provide a screenshot for folks to respond to.

**Comment by stpaultim** [comment]
I've opened repos for the Zeever related projects in the Backdrop Contrib space. 

I'm moving this discussion to the Zeever theme, because I would like to keep discussion for all of the Zeever related themes, packages, and recipes in one issue queue (during initial development). 

https://github.com/backdrop-contrib/zeever/issues/12
